title: Lahari SK Gowda  # You can add your name here

logo: /Users/mohitkumar/prsnl_projs/appDev/Laharisk_resume/laharisk/lana.jpeg # Use a relative path to logo image 

description: Technofunctional BA and Certified Scrum master. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: laharisk007@gmail.com # Allow visitors to contact you